# Generated by Django 6.0 on 2025-12-11 12:34

import django.contrib.postgres.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0004_branch_images'),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='branchId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='branch_rooms', to='branches.branch'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='description',
            field=models.CharField(default=1, max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=8),
        ),
        migrations.AddField(
            model_name='room',
            name='max_guests',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='price_per_night',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='type',
            field=models.CharField(choices=[('Classic Suite', 'Classic'), ('Supreme Suite', 'Supreme'), ('Deluxe Suite', 'Deluxe'), ('Executive Suite', 'Executive'), ('Super Executive Suite', 'Super Executive'), ('Self Catering Execuitve Suite', 'Self Cat Executive')], default='Classic Suite', max_length=50),
        ),
    ]
