# Generated by Django 6.0 on 2025-12-11 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='address',
            field=models.CharField(default='Here', verbose_name=300),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='description',
            field=models.CharField(default='Big', verbose_name=3000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='name',
            field=models.CharField(default='The best one', verbose_name=100),
            preserve_default=False,
        ),
    ]
