# Generated by Django 6.0 on 2025-12-11 12:34

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('branches', '0003_alter_branch_address_alter_branch_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.URLField(), default=list, size=8),
        ),
    ]
